config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "mini_scheduler/web"

# The following constants have been replaced with `RouteFormat` and are deprecated.
USERNAME_ROUTE_FORMAT = /[%\w.\-]+?/ unless defined?(USERNAME_ROUTE_FORMAT)
BACKUP_ROUTE_FORMAT = /.+\.(sql\.gz|tar\.gz|tgz)/i unless defined?(BACKUP_ROUTE_FORMAT)

Discourse::Application.routes.draw do
  def patch(*)
  end # Disable PATCH requests

  scope path: nil, constraints: { format: %r{(json|html|\*/\*)} } do
    relative_url_root =
      (
        if (
             defined?(Rails.configuration.relative_url_root) &&
               Rails.configuration.relative_url_root
           )
          Rails.configuration.relative_url_root + "/"
        else
          "/"
        end
      )

    match "/404", to: "exceptions#not_found", via: %i[get post]
    get "/404-body" => "exceptions#not_found_body"

    if Rails.env.test? || Rails.env.development?
      get "/bootstrap/plugin-css-for-tests.css" => "bootstrap#plugin_css_for_tests"
    end

    # This is not a valid production route and is causing routing errors to be raised in
    # the test env adding noise to the logs. Just handle it here so we eliminate the noise.
    get "/favicon.ico", to: proc { [200, {}, [""]] } if Rails.env.test?

    post "webhooks/aws" => "webhooks#aws"
    post "webhooks/mailgun" => "webhooks#mailgun"
    post "webhooks/mailjet" => "webhooks#mailjet"
    post "webhooks/mailpace" => "webhooks#mailpace"
    post "webhooks/mandrill" => "webhooks#mandrill"
    get "webhooks/mandrill" => "webhooks#mandrill_head"
    post "webhooks/postmark" => "webhooks#postmark"
    post "webhooks/sendgrid" => "webhooks#sendgrid"
    post "webhooks/sparkpost" => "webhooks#sparkpost"

    scope path: nil, format: true, constraints: { format: :xml } do
      resources :sitemap, only: [:index]
      get "/sitemap_:page" => "sitemap#page", :page => /[1-9][0-9]*/
      get "/sitemap_recent" => "sitemap#recent"
      get "/news" => "sitemap#news"
    end

    scope path: nil, constraints: { format: /.*/ } do
      if Rails.env.development?
        mount Sidekiq::Web => "/sidekiq"
        mount Logster::Web => "/logs"
      else
        # only allow sidekiq in master site
        mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new(require_master: true)
        mount Logster::Web => "/logs", :constraints => AdminConstraint.new
      end
    end

    resources :about, only: [:index] do
      collection { get "live_post_counts" }
    end

    get "finish-installation" => "finish_installation#index"
    get "finish-installation/register" => "finish_installation#register"
    post "finish-installation/register" => "finish_installation#register"
    get "finish-installation/confirm-email" => "finish_installation#confirm_email"
    put "finish-installation/resend-email" => "finish_installation#resend_email"

    get "pub/check-slug" => "published_pages#check_slug"
    get "pub/by-topic/:topic_id" => "published_pages#details"
    put "pub/by-topic/:topic_id" => "published_pages#upsert"
    delete "pub/by-topic/:topic_id" => "published_pages#destroy"
    get "pub/:slug" => "published_pages#show"

    resources :directory_items, only: [:index]

    get "site" => "site#site"
    namespace :site do
      get "settings"
      get "custom_html"
      get "banner"
      get "emoji"
    end

    get "site/basic-info" => "site#basic_info"
    get "site/statistics" => "site#statistics"

    get "srv/status" => "forums#status"

    get "wizard" => "wizard#index"
    get "wizard/steps/:id" => "wizard#index"
    put "wizard/steps/:id" => "steps#update"

    namespace :admin_revamp,
              path: "admin-revamp",
              module: "admin",
              constraints: StaffConstraint.new do
      get "" => "admin#index"
      get "config/:area" => "admin#index"
    end

    namespace :admin, constraints: StaffConstraint.new do
      get "" => "admin#index"

      get "plugins" => "plugins#index"

      resources :site_settings, only: %i[index update], constraints: AdminConstraint.new do
        collection { get "category/:id" => "site_settings#index" }

        put "user_count" => "site_settings#user_count"
      end

      get "reports" => "reports#index"
      get "reports/bulk" => "reports#bulk"
      get "reports/:type" => "reports#show"

      resources :groups, only: [:create] do
        member do
          delete "owners" => "groups#remove_owner"
          put "primary" => "groups#set_primary"
        end
      end
      resources :groups, only: [:destroy], constraints: AdminConstraint.new do
        collection { put "automatic_membership_count" => "groups#automatic_membership_count" }
      end

      resources :users, id: RouteFormat.username, only: %i[index destroy] do
        collection do
          get "list" => "users#index"
          get "list/:query" => "users#index"
          get "ip-info" => "users#ip_info"
          delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
          get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
          put "approve-bulk" => "users#approve_bulk"
        end
        delete "penalty_history", constraints: AdminConstraint.new
        put "suspend"
        put "delete_posts_batch"
        put "unsuspend"
        put "revoke_admin", constraints: AdminConstraint.new
        put "grant_admin", constraints: AdminConstraint.new
        put "revoke_moderation", constraints: AdminConstraint.new
        put "grant_moderation", constraints: AdminConstraint.new
        put "approve"
        post "log_out", constraints: AdminConstraint.new
        put "activate"
        put "deactivate"
        put "silence"
        put "unsilence"
        put "trust_level"
        put "trust_level_lock"
        put "primary_group"
        post "groups" => "users#add_group", :constraints => AdminConstraint.new
        delete "groups/:group_id" => "users#remove_group", :constraints => AdminConstraint.new
        get "badges"
        get "leader_requirements" => "users#tl3_requirements"
        get "tl3_requirements"
        put "anonymize"
        post "merge"
        post "reset-bounce-score"
        put "disable_second_factor"
        delete "sso_record"
      end
      get "users/:id.json" => "users#show", :defaults => { format: "json" }
      get "users/:id/:username" => "users#show",
          :constraints => {
            username: RouteFormat.username,
          },
          :as => :user_show
      get "users/:id/:username/badges" => "users#show"
      get "users/:id/:username/tl3_requirements" => "users#show"

      post "users/sync_sso" => "users#sync_sso", :constraints => AdminConstraint.new

      resources :impersonate, only: %i[index create], constraints: AdminConstraint.new

      resources :email, only: [:index], constraints: AdminConstraint.new do
        collection do
          post "test"
          get "sent"
          get "skipped"
          get "bounced"
          get "received"
          get "rejected"
          get "/incoming/:id" => "email#incoming"
          get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
          get "preview-digest" => "email#preview_digest"
          post "send-digest" => "email#send_digest"
          get "smtp_should_reject"
          post "handle_mail"
          get "advanced-test"
          post "advanced-test" => "email#advanced_test"
        end
      end

      scope "/logs" do
        resources :staff_action_logs, only: [:index]
        get "staff_action_logs/:id/diff" => "staff_action_logs#diff"
        resources :screened_emails, only: %i[index destroy]
        resources :screened_ip_addresses, only: %i[index create update destroy]
        resources :screened_urls, only: [:index]
        resources :search_logs, only: [:index]
        get "search_logs/term/" => "search_logs#term"
      end

      get "/logs" => "staff_action_logs#index"

      # alias
      get "/logs/watched_words", to: redirect(relative_url_root + "admin/customize/watched_words")
      get "/logs/watched_words/*path",
          to: redirect(relative_url_root + "admin/customize/watched_words/%{path}")

      get "customize" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/themes" => "themes#index", :constraints => AdminConstraint.new
      get "customize/theme-components" => "themes#index", :constraints => AdminConstraint.new
      get "customize/colors" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/colors/:id" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/permalinks" => "permalinks#index", :constraints => AdminConstraint.new
      get "customize/embedding" => "embedding#show", :constraints => AdminConstraint.new
      put "customize/embedding" => "embedding#update", :constraints => AdminConstraint.new

      resources :themes,
                only: %i[index create show update destroy],
                constraints: AdminConstraint.new do
        member do
          get "preview" => "themes#preview"
          put "setting" => "themes#update_single_setting"
        end
        collection do
          post "import" => "themes#import"
          post "upload_asset" => "themes#upload_asset"
          post "generate_key_pair" => "themes#generate_key_pair"
          delete "bulk_destroy" => "themes#bulk_destroy"
        end
      end

      scope "/customize", constraints: AdminConstraint.new do
        resources :user_fields,
                  only: %i[index create update destroy],
                  constraints: AdminConstraint.new
        resources :emojis, only: %i[index create destroy], constraints: AdminConstraint.new
        resources :form_templates, constraints: AdminConstraint.new, path: "/form-templates" do
          collection { get "preview" => "form_templates#preview" }
        end

        get "themes/:id/:target/:field_name/edit" => "themes#index"

app/controllers/finish_installation_controller.rb
# frozen_string_literal: true

class FinishInstallationController < ApplicationController
  skip_before_action :check_xhr, :preload_json, :redirect_to_login_if_required
  layout "finish_installation"

  before_action :ensure_no_admins, except: %w[confirm_email resend_email]

  def index
  end

  def register
    @allowed_emails = find_allowed_emails

    @user = User.new
    if request.post?
      email = params[:email].strip
      raise Discourse::InvalidParameters.new unless @allowed_emails.include?(email)

      if existing_user = User.find_by_email(email)
        @user = existing_user
        send_signup_email
        return redirect_confirm(email)
      end

      @user.email = email
      @user.username = params[:username]
      @user.password = params[:password]
      @user.password_required!

      if @user.save
        @user.change_trust_level!(1) if @user.trust_level < 1
        send_signup_email
        redirect_confirm(@user.email)
      end
    end
  end

  def confirm_email
    @email = session[:registered_email]
  end

  def resend_email
    @email = session[:registered_email]
    @user = User.find_by_email(@email)
    send_signup_email if @user.present?
  end

  protected

  def send_signup_email
    return if @user.active && @user.email_confirmed?

    email_token = @user.email_tokens.create!(email: @user.email, scope: EmailToken.scopes[:signup])
    EmailToken.enqueue_signup_email(email_token)
  end

  def redirect_confirm(email)
    session[:registered_email] = email
    redirect_to(finish_installation_confirm_email_path)
  end

  def find_allowed_emails
    unless GlobalSetting.respond_to?(:developer_emails) && GlobalSetting.developer_emails.present?
      return []
    end
    GlobalSetting.developer_emails.split(",").map(&:strip)
  end

  def ensure_no_admins
    preload_anonymous_data
    raise Discourse::InvalidAccess.new unless SiteSetting.has_login_hint?
  end
end

app/views/finish_installation/confirm_email.html.erb
<h1><%= t 'finish_installation.confirm_email.title' %></h1>

<%= raw(t 'finish_installation.confirm_email.message', email: @email) %>

<div class='row'>
  <%= button_to(finish_installation_resend_email_path, method: :put, class: 'wizard-container__button primary') do %>
    <%= t 'finish_installation.resend_email.title' %>
  <% end %>
</div>

app/views/finish_installation/index.html.erb
<div class="wizard-congratulations-wrap">
  <div class='row'>
    <h1><%= t 'finish_installation.congratulations' %></h1>
    <p><%= t 'finish_installation.register.help' %></p>

    <%= link_to(finish_installation_register_path, class: 'wizard-container__button primary') do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="14px" height="14px" viewBox="0 0 448 512">
        <path fill="currentColor" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"></path>
      </svg>
      <%= t 'finish_installation.register.button' %>
    <% end %>

  </div>

  <div class='row finish-installation-image'>
    <img src="<%= Discourse.base_path + '/images/wizard/tada.svg' %>" alt="tada emoji" class="tada">
  </div>
</div>

app/views/finish_installation/register.html.erb
<h1><%= t 'finish_installation.register.title' %></h1>

<%- if @allowed_emails.present? %>
  <%= form_tag(finish_installation_register_path, class:"wizard-container__fields") do %>

    <div class='wizard-container__input wizard-container__field text-field'>
      <label for="email">
        <span class="wizard-container__label"><%= t 'js.user.email.title' %></span>
      </label>

      <div class='input-area'>
        <!--email_off-->
        <%= select_tag :email, options_for_select(@allowed_emails, selected: params[:email]), class: 'combobox wizard-container__combobox' %>
        <!--/email_off-->
      </div>
    </div>

    <div class='wizard-container__input wizard-container__field text-field <% if @user.errors[:username].present? %>invalid<% end %>'>
      <label for="username">
        <span class="wizard-container__label"><%= t 'js.user.username.title' %></span>
      </label>

      <div class='wizard-container__description'><%= t 'js.user.username.instructions' %></div>

      <div class='input-area'>
        <%= text_field_tag(:username, params[:username], class:"wizard-container__text-input") %>
      </div>
      <%- @user.errors[:username].each do |e| %>
        <div class='field-error-description'><%= e.to_s %></div>
      <%- end %>
    </div>

    <div class='wizard-container__input wizard-container__field text-field <% if @user.errors[:username].present? %>invalid<% end %>'>
      <label for="password">
        <span class="wizard-container__label"><%= t 'js.user.password.title' %></span>
      </label>

      <div class='wizard-container__description'><%= t 'js.user.password.instructions', count: SiteSetting.min_admin_password_length  %></div>

      <div class='input-area'>
        <%= password_field_tag(:password, params[:password], class:"wizard-container__text-input") %>
      </div>
      <% @user.errors[:password].each do |e| %>
        <div class='field-error-description'><%= e.to_s %></div>
      <% end %>
    </div>

    <%= submit_tag(t('finish_installation.register.button'), class: 'wizard-container__button primary') %>

  <%- end %>
<%- else -%>
  <p><%= raw(t 'finish_installation.register.no_emails') %></p>
<%- end %>

app/views/finish_installation/resend_email.html.erb
<h1><%= t 'finish_installation.resend_email.title' %></h1>

<%= raw(t 'finish_installation.resend_email.message', email: @email) %>